#任渊生存服务端功能核心插件
#此插件集成了一些我自己写的功能和服务端数据统计
#你可以在 https://github.com/lRENyaaa/RenYuan-Core 查看本插件源代码

#防爆模块
NotBoom:
  #是否启用
  Enable: true
  #true开启保护 false关闭保护
  #TNT爆炸
  TNT: true
  #末影水晶爆炸
  EnderCrystal: true
  #苦力怕爆炸
  Creeper: true
  #凋零头爆炸
  WitherSkull: true
  #凋零生成爆炸
  Wither: true
  #火焰弹爆炸
  FireBall: true
  #TNT矿车
  TNTMinecart: true
  #凋零破坏
  WitherDestroy: true
  #方块爆炸(重生锚和床)
  BlockExplode: true
  #其他爆炸(未知原因的)
  Other: false

#本服务端使用CStats来获取服务端使用统计
#数据统计可以前往 http://cstats.iroselle.com/plugin/bukkit/RenYuan-Core 查看
Metrics:
  Enable: true

#基岩版玩家名称保护
#这是用于防止Java版玩家使用基岩版玩家前缀进入服务器的
#因为在同一个UUID下不同玩家名称可能会导致未知的问题
#你如果对Floodgate插件的详细功能不够清楚,请不要动它
AntiUserName:
  Enable: true

#启用防讲台崩服
#如果你已经使用了具有类似效果的插件,可以关闭它
LecternCrashFix:
  Enable: true

#自定义插件所发送的信息
Message:
  #发送信息时的前缀
  Prefix: "§f[§6服务器§f] "
  #回到主城的提示
  PlayerSpawn: "已将你传送到主城"
  #非玩家使用回主城指令的提示
  ConsoleSpawn: "仅玩家可执行该命令"

#主城相关
Spawn:
  #是否启用,如果你已经安装了相似功能的主城插件可以关闭
  Enable: true
  #是否启用主城保护,如果你没安装保护类插件则不建议关闭
  Protect: true
  #是否关闭主城伤害,除了kill以外所有伤害将会被全部禁用,包括虚空
  NoDamage: true
  #是否锁定出生点,每次重生都会回到主城而不是这个世界的出生点
  LockSpawn: true
  #主城的世界名
  World: "spawn"
  #主城坐标
  X: 79.5
  Y: 105.0
  Z: -149.5