#任渊生存服务端功能核心插件
#此插件集成了一些我自己写的功能和服务端数据统计

#防爆模块
NotBoom:
  #是否启用
  Enable: true
  #true开启保护 false关闭保护
  #TNT爆炸
  TNT: true
  #末影水晶爆炸
  EnderCrystal: true
  #苦力怕爆炸
  Creeper: true
  #凋零头爆炸
  WitherSkull: true
  #凋零生成爆炸
  Wither: true
  #火焰弹爆炸
  FireBall: true
  #TNT矿车
  TNTMinecart: true
  #凋零破坏
  WitherDestroy: true
  #方块爆炸(重生锚和床)
  BlockExplode: true
  #其他爆炸(未知原因的)
  Other: false

#本服务端使用CStats来获取服务端使用统计
#数据统计可以前往 http://cstats.iroselle.com/plugin/bukkit/RenYuan-Core 查看
Metrics:
  Enable: true

#基岩版玩家名称保护
#这是用于防止Java版玩家使用基岩版玩家前缀进入服务器的
#因为在同一个UUID下不同玩家名称可能会导致未知的问题
#你如果对Floodgate插件的详细功能不够清楚,请不要动它
AntiUserName:
  Enable: true